### ISSUE TITLE
nested server.rows

### ISSUE THREAD

**Issue by eugwne** [pllua/pllua-deprecated#1]
In case:
do
$$
for left in server.rows('select generate_series as v from generate_series(1,2) ') do
    print('left',left.v)
    for right in server.rows('select generate_series as d from generate_series(1,2) ') do
        print('right',right.d)
    end
end
$$
language pllua
out:
INFO:  left 1
INFO:  right    1
INFO:  right    2
INFO:  left nil
INFO:  right    1
INFO:  right    2

server.rows with "v" loses information about the table, when it has nested rows

**Comment by golgote** [comment]
I can confirm that. I don't know yet how to fix it so if you have any idea, please let me know. Thanks.

**Comment by eugwne** [comment]
Actually, it's not only the problem of server.rows, some query saved tupdesc at InvalidOid LUA_REGISTRYINDEX (server.execute for example). I've been thinking about rewriting that using some kind of refcounted table info. Also luaP_rowsaux has no SPI_freetuptable(SPI_tuptable).

**Comment by golgote** [comment]
I agree that the current use of LUA_REGISTRYINDEX seems broken. I had to partially remove it in my last commit about triggers but I couldn't get rid of it completely because it is used as some kind of cache to share table attributes between function calls. It is probably a good idea to get rid of it or to fix how it is used. Please feel free to make a pull request or send a patch if you can fix some bugs.

**Comment by golgote** [comment]
Looks good. I will test it next week and let you know.
