### ISSUE TITLE
Clarify project status

### ISSUE THREAD

**Issue by daurnimator** [pllua/pllua-deprecated#21]
This seems to be the only live fork of pllua I can find. What is the status of this?

Has there been any contact with Luis Carvalho about an official take over of the project? (which may involve shutting down [the pgfoundry page](http://pgfoundry.org/projects/pllua), updating [the website](http://pllua.projects.pgfoundry.org/) and taking ownership of distro packages: https://packages.debian.org/sid/postgresql-9.5-pllua http://wiki.alpinelinux.org/wiki/Pllua)

Furthermore, it appears that this repo is missing the true CVS history between 0.3.2 and [the 1.0 release](http://pgfoundry.org/frs/shownotes.php?release_id=2037)?

**Comment by daurnimator** [comment]
@carvalho ping?

**Comment by golgote** [comment]
Luis is not working on pllua anymore AFAIK. I imported the last version I could find in the old CVS, so I think it is 1.0.

With @eugwne , we have been maintaining it so that it would compile with the latest PG releases. We also added some interesting features like pgfunc, subtransactions, more triggers info, better registry, better errors (all mostly added by @eugwne ) and improvements. Our strategy so far has been to add features we needed when we needed them. At the moment, we have some problems with Luajit not being used in trusted version (pllua vs plluau), see #16 . Other than that, it's running fine.

I am personally using pllua on some DB in production and it is faster, lighter and cooler to use than plpgsql. So this version has a test suite and is currently being maintained.

**Comment by studdugie** [comment]
I'm here too but I'm not contributing any code. I'm just a humble user who
is happy to see that it is being maintained.

Dane

On Mon, Mar 14, 2016 at 10:41 AM, Bertrand Mansion <notifications@github.com

**Comment by mbalmer** [comment]
FWIW, I am using PL/Lua in a commercial product where we use Lua on the client side (using arcapos/luapgsql).

**Comment by daurnimator** [comment]
Not sure if this should have been closed?
Would be good to track info about take-over old urls/packages.

**Comment by golgote** [comment]
It's not really an issue neither. If we keep issues open, it might give a bad image too. This may be better as a wiki page.

**Comment by mbalmer** [comment]
> Am 23.03.2016 um 08:47 schrieb Bertrand Mansion notifications@github.com:
> 
> It's not really an issue neither. If we keep issues open, it might give a bad image too. This may be better as a wiki page.

Indeed. Issues should rather be about code.  A „what’s happening in PL/Lua“ wiki, otoh, could be nice.

**Comment by golgote** [comment]
I have created the page here:
https://github.com/pllua/pllua/wiki
